config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
  validates :cuteness, presence: true, numericality: { in: 1..10 }
  validates :softness, presence: true, numericality: { in: 1..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: "You created a kitten! Congrats!"
    else
      render :new, status: :unprocessable_entity, alert: "Meow Meow! Kitten wasn't created!!"
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "You updated a kitten! Congrats!"
    else
      render :edit, status: :unprocessable_entity, alert: "Meow Meow! Kitten wasn't updated!!"
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other, notice: "You removed a kitten! Congrats!"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% kitten.errors.full_messages_for(:name).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.text_field :age %>
    <% kitten.errors.full_messages_for(:age).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :cuteness %>
    <%= form.text_field :cuteness %>
    <% kitten.errors.full_messages_for(:cuteness).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :softness %>
    <%= form.text_field :softness %>
    <% kitten.errors.full_messages_for(:softness).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "form", kitten: @kitten %>
<li><%= link_to "Destroy", kitten_path(@kitten), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %></li>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
  <li>
    <%= link_to kitten.name, kitten %>
  </li>
  <ul>
    <li><%= link_to "Destroy", kitten_path(kitten), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %></li>
  </ul>
  <% end %>
</ul>

<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<%= link_to "Home", root_path %>
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<ul>
  <li><%= link_to "Edit", edit_kitten_path(@kitten) %></li>
  <li><%= link_to "Destroy", kitten_path(@kitten), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>